/**
 * Generate db/seed.sql from the committed src/data/machines.json.
 *
 * This is the one-time bridge out of the workbook: the Excel pipeline produced
 * machines.json, and machines.json seeds the database. After that Postgres is
 * the source of truth and Machine/Machines.xlsx becomes an archive.
 *
 * It writes SQL rather than connecting to a database on purpose — no driver
 * dependency, nothing to configure, and the result is a plain text file that
 * can be read and reviewed before anything touches a live server.
 *
 *   node db/make-seed.mjs          # -> db/seed.sql
 *   psql "$PGCONNSTRING" -f db/seed.sql
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { extractSource } from '../src/lib/derive.js'

const payload = JSON.parse(readFileSync(new URL('../src/data/machines.json', import.meta.url)))
const src = extractSource(payload)

const q = (v) => (v == null ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`)
const n = (v) => (v == null || Number.isNaN(v) ? 'NULL' : String(v))
const b = (v) => (v ? 'true' : 'false')

const out = []
out.push('-- Generated by db/make-seed.mjs — do not edit by hand.')
out.push(`-- Source: ${src.source}`)
out.push('')
out.push('BEGIN;')
out.push('')
out.push('-- Idempotent: re-running replaces the data rather than duplicating it.')
out.push('TRUNCATE curve_points, machines, rules, equipment CASCADE;')
out.push('')

for (const m of src.machines) {
  out.push(
    `INSERT INTO machines (id, name, model, function, holders, gf_size, gf_per_holder, yield, has_open_marker) VALUES (` +
      [q(m.id), q(m.name), q(m.model), q(m.function), n(m.holders), q(m.gfSize),
       n(m.gfPerHolder), n(m.yield), b(m.hasOpenMarker)].join(', ') +
      ');',
  )
}
out.push('')

for (const m of src.machines) {
  const values = m.measured.map((p) => `(${q(m.id)}, ${n(p.t)}, ${n(p.T)})`)
  out.push(`INSERT INTO curve_points (machine_id, t_hours, temp_c) VALUES`)
  out.push('  ' + values.join(',\n  ') + ';')
  out.push('')
}

src.ruleSentences.forEach((text, i) => {
  out.push(`INSERT INTO rules (id, text) VALUES (${i}, ${q(text)});`)
})
out.push('')

for (const e of src.equipment) {
  out.push(
    `INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES (` +
      [q(e.id), q(e.name), n(e.maxAmps), b(e.rated), b(e.needsInput)].join(', ') +
      ');',
  )
}
out.push('')
out.push('COMMIT;')
out.push('')

const target = new URL('./seed.sql', import.meta.url)
writeFileSync(target, out.join('\n'), 'utf8')

const points = src.machines.reduce((a, m) => a + m.measured.length, 0)
console.log(
  `wrote db/seed.sql — ${src.machines.length} machines, ${points} curve points, ` +
    `${src.ruleSentences.length} rules, ${src.equipment.length} equipment rows`,
)
