-- Generated by db/make-seed.mjs — do not edit by hand.
-- Source: Machines.xlsx

BEGIN;

-- Idempotent: re-running replaces the data rather than duplicating it.
TRUNCATE curve_points, machines, rules, equipment CASCADE;

INSERT INTO machines (id, name, model, function, holders, gf_size, gf_per_holder, yield, has_open_marker) VALUES ('furnace-1', 'Furnace 1', 'Vertical 500', 'Graphitization', 2, '300x300', 660, 0.9, true);
INSERT INTO machines (id, name, model, function, holders, gf_size, gf_per_holder, yield, has_open_marker) VALUES ('furnace-2', 'Furnace 2', 'Vertical 500', 'Graphitization', 2, '300x300', 660, 0.9, true);
INSERT INTO machines (id, name, model, function, holders, gf_size, gf_per_holder, yield, has_open_marker) VALUES ('furnace-3', 'Furnace 3', 'Horizontal 500', 'Carbonization', 3, '300x300', 660, 0.9, false);
INSERT INTO machines (id, name, model, function, holders, gf_size, gf_per_holder, yield, has_open_marker) VALUES ('furnace-4', 'Furnace 4', 'Horizontal 500', 'Carbonization', 3, '300x300', 660, 0.9, false);
INSERT INTO machines (id, name, model, function, holders, gf_size, gf_per_holder, yield, has_open_marker) VALUES ('furnace-5', 'Furnace 5', 'Horizontal 500', 'Graphitization', 3, '300x300', 660, 0.9, true);
INSERT INTO machines (id, name, model, function, holders, gf_size, gf_per_holder, yield, has_open_marker) VALUES ('furnace-6', 'Furnace 6', 'Horizontal 500', 'Graphitization', 3, '300x300', 660, 0.9, true);

INSERT INTO curve_points (machine_id, t_hours, temp_c) VALUES
  ('furnace-1', 0, 20),
  ('furnace-1', 1, 1000),
  ('furnace-1', 2, 1450),
  ('furnace-1', 3, 1600),
  ('furnace-1', 4, 1800),
  ('furnace-1', 5, 1900),
  ('furnace-1', 6, 2050),
  ('furnace-1', 7, 2200),
  ('furnace-1', 8, 2330),
  ('furnace-1', 9, 2460),
  ('furnace-1', 10, 2580),
  ('furnace-1', 11, 2700),
  ('furnace-1', 12, 2800),
  ('furnace-1', 13, 2800),
  ('furnace-1', 14, 2700),
  ('furnace-1', 15, 2320),
  ('furnace-1', 16, 1823),
  ('furnace-1', 17, 1634),
  ('furnace-1', 18, 1471),
  ('furnace-1', 19, 1328),
  ('furnace-1', 20, 1199),
  ('furnace-1', 21, 1084),
  ('furnace-1', 22, 1000),
  ('furnace-1', 34, 300);

INSERT INTO curve_points (machine_id, t_hours, temp_c) VALUES
  ('furnace-2', 0, 20),
  ('furnace-2', 1, 1000),
  ('furnace-2', 2, 1450),
  ('furnace-2', 3, 1600),
  ('furnace-2', 4, 1800),
  ('furnace-2', 5, 1900),
  ('furnace-2', 6, 2050),
  ('furnace-2', 7, 2200),
  ('furnace-2', 8, 2330),
  ('furnace-2', 9, 2460),
  ('furnace-2', 10, 2580),
  ('furnace-2', 11, 2700),
  ('furnace-2', 12, 2800),
  ('furnace-2', 13, 2800),
  ('furnace-2', 14, 2700),
  ('furnace-2', 15, 2320),
  ('furnace-2', 16, 1823),
  ('furnace-2', 17, 1634),
  ('furnace-2', 18, 1471),
  ('furnace-2', 19, 1328),
  ('furnace-2', 20, 1199),
  ('furnace-2', 21, 1084),
  ('furnace-2', 22, 1000),
  ('furnace-2', 34, 300);

INSERT INTO curve_points (machine_id, t_hours, temp_c) VALUES
  ('furnace-3', 0, 24),
  ('furnace-3', 1, 157),
  ('furnace-3', 2, 250),
  ('furnace-3', 3, 457),
  ('furnace-3', 4, 650),
  ('furnace-3', 5, 757),
  ('furnace-3', 6, 800),
  ('furnace-3', 7, 1000),
  ('furnace-3', 8, 1000),
  ('furnace-3', 9, 978),
  ('furnace-3', 10, 895),
  ('furnace-3', 11, 826),
  ('furnace-3', 12, 765),
  ('furnace-3', 13, 710),
  ('furnace-3', 14, 661),
  ('furnace-3', 15, 616),
  ('furnace-3', 16, 575),
  ('furnace-3', 17, 538),
  ('furnace-3', 18, 503),
  ('furnace-3', 19, 470),
  ('furnace-3', 20, 440),
  ('furnace-3', 21, 411),
  ('furnace-3', 22, 385),
  ('furnace-3', 23, 359),
  ('furnace-3', 24, 336),
  ('furnace-3', 25, 314),
  ('furnace-3', 26, 293),
  ('furnace-3', 27, 274),
  ('furnace-3', 28, 256),
  ('furnace-3', 29, 238),
  ('furnace-3', 30, 223),
  ('furnace-3', 31, 208),
  ('furnace-3', 32, 194),
  ('furnace-3', 33, 181),
  ('furnace-3', 34, 169),
  ('furnace-3', 35, 158),
  ('furnace-3', 36, 148),
  ('furnace-3', 37, 138);

INSERT INTO curve_points (machine_id, t_hours, temp_c) VALUES
  ('furnace-4', 0, 24),
  ('furnace-4', 1, 157),
  ('furnace-4', 2, 250),
  ('furnace-4', 3, 457),
  ('furnace-4', 4, 650),
  ('furnace-4', 5, 757),
  ('furnace-4', 6, 800),
  ('furnace-4', 7, 1000),
  ('furnace-4', 8, 1000),
  ('furnace-4', 9, 978),
  ('furnace-4', 10, 895),
  ('furnace-4', 11, 826),
  ('furnace-4', 12, 765),
  ('furnace-4', 13, 710),
  ('furnace-4', 14, 661),
  ('furnace-4', 15, 616),
  ('furnace-4', 16, 575),
  ('furnace-4', 17, 538),
  ('furnace-4', 18, 503),
  ('furnace-4', 19, 470),
  ('furnace-4', 20, 440),
  ('furnace-4', 21, 411),
  ('furnace-4', 22, 385),
  ('furnace-4', 23, 359),
  ('furnace-4', 24, 336),
  ('furnace-4', 25, 314),
  ('furnace-4', 26, 293),
  ('furnace-4', 27, 274),
  ('furnace-4', 28, 256),
  ('furnace-4', 29, 238),
  ('furnace-4', 30, 223),
  ('furnace-4', 31, 208),
  ('furnace-4', 32, 194),
  ('furnace-4', 33, 181),
  ('furnace-4', 34, 169),
  ('furnace-4', 35, 158),
  ('furnace-4', 36, 148),
  ('furnace-4', 37, 138);

INSERT INTO curve_points (machine_id, t_hours, temp_c) VALUES
  ('furnace-5', 0, 20),
  ('furnace-5', 1, 1000),
  ('furnace-5', 2, 1450),
  ('furnace-5', 3, 1600),
  ('furnace-5', 4, 1800),
  ('furnace-5', 5, 1900),
  ('furnace-5', 6, 2050),
  ('furnace-5', 7, 2200),
  ('furnace-5', 8, 2330),
  ('furnace-5', 9, 2460),
  ('furnace-5', 10, 2580),
  ('furnace-5', 11, 2700),
  ('furnace-5', 12, 2800),
  ('furnace-5', 13, 2800),
  ('furnace-5', 14, 2700),
  ('furnace-5', 15, 2320),
  ('furnace-5', 16, 1823),
  ('furnace-5', 17, 1634),
  ('furnace-5', 18, 1471),
  ('furnace-5', 19, 1328),
  ('furnace-5', 20, 1199),
  ('furnace-5', 21, 1084),
  ('furnace-5', 22, 1000),
  ('furnace-5', 34, 300);

INSERT INTO curve_points (machine_id, t_hours, temp_c) VALUES
  ('furnace-6', 0, 20),
  ('furnace-6', 1, 1000),
  ('furnace-6', 2, 1450),
  ('furnace-6', 3, 1600),
  ('furnace-6', 4, 1800),
  ('furnace-6', 5, 1900),
  ('furnace-6', 6, 2050),
  ('furnace-6', 7, 2200),
  ('furnace-6', 8, 2330),
  ('furnace-6', 9, 2460),
  ('furnace-6', 10, 2580),
  ('furnace-6', 11, 2700),
  ('furnace-6', 12, 2800),
  ('furnace-6', 13, 2800),
  ('furnace-6', 14, 2700),
  ('furnace-6', 15, 2320),
  ('furnace-6', 16, 1823),
  ('furnace-6', 17, 1634),
  ('furnace-6', 18, 1471),
  ('furnace-6', 19, 1328),
  ('furnace-6', 20, 1199),
  ('furnace-6', 21, 1084),
  ('furnace-6', 22, 1000),
  ('furnace-6', 34, 300);

INSERT INTO rules (id, text) VALUES (0, 'Furnace 1 and Furnace 2 cannot heat at the same time');
INSERT INTO rules (id, text) VALUES (1, 'Furnace 1 and Furnace 3 cannot heat at the same time');
INSERT INTO rules (id, text) VALUES (2, 'Furnace 2 and Furnace 3 cannot heat at the same time');
INSERT INTO rules (id, text) VALUES (3, 'Furnace 4 and Furnace 6 cannot heat at the same time');
INSERT INTO rules (id, text) VALUES (4, 'Furnace 4 and Furnace 5 cannot heat at the same time');
INSERT INTO rules (id, text) VALUES (5, 'Furnace 5 and Furnace 6 cannot heat at the same time');
INSERT INTO rules (id, text) VALUES (6, 'It takes one hour to load a furnace before heating');
INSERT INTO rules (id, text) VALUES (7, 'It takes one hour to unload a furnace after cooling');
INSERT INTO rules (id, text) VALUES (8, 'Cooling system 1 need to run during both heating and cooling for furnace 1, furnace 2 and furnace 3');
INSERT INTO rules (id, text) VALUES (9, 'Cooling system 2 needs to run during both heating and cooling for furnace 4, furnace 5 and furnace 6');
INSERT INTO rules (id, text) VALUES (10, 'Vacuum system 01 needs to run during both heating and cooling for furnace 3');
INSERT INTO rules (id, text) VALUES (11, 'Vacuum system 02 needs to run during both heating and cooling for furnace 4');
INSERT INTO rules (id, text) VALUES (12, 'Run coating line as much as possible');
INSERT INTO rules (id, text) VALUES (13, 'Coating line needs 200A electricity during first 2 hours, then 100A for continuous running. If it stops, then it has to heat up again with 200A for 2 hours');

INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('coating-line', 'Coating line', 250, true, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('furnace-1', 'Furnace 1', 330, true, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('furnace-2', 'Furnace 2', 330, true, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('furnace-3', 'Furnace 3', 150, true, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('vacuum-system-01', 'Vacuum system 01', 40, true, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('vacuum-system-02', 'Vacuum system 02', 40, true, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('furnace-4', 'Furnace 4', NULL, false, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('furnace-5', 'Furnace 5', NULL, false, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('furnace-6', 'Furnace 6', NULL, false, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('furnace-7', 'Furnace 7', 82, true, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('cooling-system-1', 'Cooling system 1', 41, true, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('cooling-system-2', 'Cooling system 2', 45, true, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('pre-treatment', 'Pre treatment', 45, true, false);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('r-d', 'R&D', NULL, false, true);
INSERT INTO equipment (id, name, max_amps, rated, needs_input) VALUES ('facility', 'Facility', NULL, false, true);

COMMIT;
